[versions]

kotlin = "1.6.20"

detekt = "1.20.0"
diktat = "1.1.0"
buildconfig = "3.0.3"
dokka = "1.7.0"
intellij = "1.10.0"
xenomachina = "2.0.7"
kotlinx = "0.8.0"
junit-jupiter = "5.8.2"
junit-platform = "1.8.2"
jgrapht = "1.5.1"
protobuf = "3.19.4"
protobuf-plugin = "0.8.13"
gumtreediff = "3.0.0"
zip4j = "2.11.1"
fastutil = "8.5.11"
guava = "31.1-jre"
plugin-utilities = "1.0"

[libraries]
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
diktat-gradle-plugin = { module = "org.cqfn.diktat:diktat-gradle-plugin", version.ref = "diktat" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-argparser = { module = "com.xenomachina:kotlin-argparser", version.ref = "xenomachina" }
dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "kotlinx" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-platform-console = { module = "org.junit.platform:junit-platform-console", version.ref = "junit-platform" }
jgrapht-core = { module = "org.jgrapht:jgrapht-core", version.ref = "jgrapht" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-plugin = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobuf-plugin" }
gumtreediff-core = { module = "com.github.gumtreediff:core", version.ref = "gumtreediff" }
gumtreediff-gen-python = { module = "com.github.gumtreediff:gen.python", version.ref = "gumtreediff" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
fastutil = { module = "it.unimi.dsi:fastutil-core", version.ref = "fastutil" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

plugin-utilities-core = { module = "org.jetbrains.research:plugin-utilities-core", version.ref = "plugin-utilities" }
plugin-utilities-test = { module = "org.jetbrains.research:plugin-utilities-test", version.ref = "plugin-utilities" }
plugin-utilities-python = { module = "org.jetbrains.research:plugin-utilities-python", version.ref = "plugin-utilities" }

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij = { id = "org.jetbrains.intellij", version.ref = "intellij" }


